/// <reference path="stone/PipeStone.ts" />
/// <reference path="cobble/PipeCobble.ts" />
/// <reference path="sandstone/PipeSandstone.ts" />
/// <reference path="gold/PipeGold.ts" />
/// <reference path="wooden/PipeWooden.ts" />
/// <reference path="quartz/PipeQuartz.ts" />
/// <reference path="void/PipeVoid.ts" />
/// <reference path="diamond/PipeDiamond.ts" />
/// <reference path="iron/PipeIron.ts" />

const cobblePipe = new PipeCobble();
const stonePipe = new PipeStone();
const sandstonePipe = new PipeSandstone();
const quartzPipe = new PipeQuartz();
const goldPipe = new PipeGold();
const woodPipe = new PipeWooden();
const voidPipe = new PipeVoid();
const ironPipe = new PipeIron();
const diamondPipe = new PipeDiamond();